# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: '<i class="fas fa-bars"></i>'
  #   identifier: menu
  #   weight: 0
  - name: About
    url: '#about'
    weight: 1
  - name: Technical
    url: '#technical'
    weight: 2
  - name: Languages
    url: '#languages'
    weight: 3

main_right:
  - name: Research
    url: '/research'
    weight: 1
  - name: Teaching
    url: '/teaching'
    weight: 2
  - name: Coursework
    url: '/coursework'
    weight: 3
  # - name: Contact
  #   url: '#contact'
  #   weight: 9

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  # - name: CV
  #   url: /uploads/AraPatvakanianResume.pdf
  #   weight: 80
